schema_version: 1

context:
  version: "0.14.0"

package:
  name: nxsblisswriter
  version: ${{ version }}

source:
  url: https://github.com/nexdatas/nxsblisswriter/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7b7735c5d5362e02727fd6e8c5ea682f3eda436c37ee666394de4fff4dcba1a8

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61
    - pip
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy
    - lxml
    - pytango
    - pninexus
    - blissdata

tests:
  - python:
      imports:
        - nxsblisswriter
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - if: unix
        then:
          - test -x "$PREFIX/bin/NXSBlissWriter"
          - NXSBlissWriter --help
    requirements:
      run:
        - python ${{ python_min }}.*


about:
  homepage: https://nexdatas.github.io/nxsblisswriter
  repository: https://github.com/nexdatas/nxsblisswriter
  license: GPL-3.0-or-later
  license_file: COPYRIGHT
  summary: NeXuS BlissData Writer Server
  description: |
    NeXuS BlissData Writer Server is a Tango Server which allows to write NeXus file
    from (meta)data stored in BlissData by NXSDataWriter tango server

extra:
  recipe-maintainers:
    - jkotan
